name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build app bundle
        run: ./scripts/bundle-mac.sh

      - name: Create release archive
        run: |
          cd target/release/
          tar -czf "../../Chroma-Tuner-${{ github.ref_name }}-macOS.tar.gz" "Chroma Tuner.app"
          cd ../../

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Chroma-Tuner-${{ github.ref_name }}-macOS.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}